name: Push main

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Which ref should be checked out?"
  push:
    branches:
      - main

jobs:
  test:
    name: Test & Staticcheck
    uses: ./.github/workflows/workflow_call_test.yml
    with:
      ref: ${{ inputs.ref }}
    permissions:
      contents: read

  build_push:
    name: Build & Push
    uses: ./.github/workflows/workflow_call_build_push.yml
    needs: test
    with:
      ref: ${{ inputs.ref }}
    permissions:
      id-token: write
      contents: read
