name: 'Reusable: Test & Staticcheck'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: "Which ref should be checked out?"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: Setting up Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Running Tests
        run: go test ./...

  staticcheck:
    name: Staticcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: Setting up Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Running Staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: latest

