name: 'Reusable: Test & Lint'

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: "Which ref should be checked out?"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setting up Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Running Tests
        run: go test ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setting up Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Linting Code
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
